apiVersion: v1
kind: Service
metadata:
  name: flask-docker-example-service
spec:
  type: LoadBalancer
  selector:
    app: flask-docker-example
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: web